### PR TITLE
Allow to treat unreachable lights as Off instead of On

### PR DESCRIPTION
**Pull request by nonolk**
As many other people, I do have real switch with connected bulb. And I was not happy with the actual solution which is treating unreachable bulb as On, so I modified your plugin to add a parameter to switch the behaviour.

By default it stay the same, but if you activate this parameter and the bulb will treated as Off when unreachable.

I hope you will find this useful.

### CODE REVIEW

**Comment by Smanar** [comment]
Ha ?
>The actual solution which is treating unreachable bulb as On

Are you sure ? it s not just the last state visible ?

But your are right, don't need a setting for that, it s logic too for me.

**Comment by nonolk** [comment]
Hello Smanar,

Yes I’m totally sure, if you want we either set the default value to true, to let the possibility to keep the old behaviour. Other wise I can remove the switch and set it as default. 

Best regards,

**Comment by Smanar** [comment]
Hello,

Effectively, I have just made a test, haven't found why, but I have a an unrechable light that is "on".
Seriously, you have a situation where setting the device "on" have an advantage ? for me not.

So yes, if you can remove the switch, and set if as "off" by defaut on "Command Error" pls.

And can you make the PR on beta branch pls ? Some plugins monitor the master branch github so every change trigger update on domoticz.

**Comment by Smanar** [comment]
Oups, sorry forgot you, No notifications.

Perfect, thx ^^.

**Pull request merged**
