### PR TITLE
Add Tradfri Switch support

### PR DESCRIPTION
**Pull request by erwan2345**
the switch generic profile does not work with the Ikea Tradfri Switch. This modification handle this kind of switch by supporting the short press and long press + release of the On and Off button

See the  picture of the remote:
tradfri-clicker_sq

### CODE REVIEW

**Comment by Smanar** [comment]
So first, thx a lot, I haven't all possible devices to make that you have done.
Secondly, nice catch for the line 654 modification, you already have a bug on this line ?

Sadly, you forget to switch to beta branch ^^, I can't change the master version because it will force an update for users that use the domoticz plugin manager.

I m sorry, but can you make the pull request from your fork to the beta branch ? on your fork you already have the beta version, just edit theses one and remake the pull pls. On my side the last version is on beta branch too.

**Comment by Smanar** [comment]
Are you still here :) ?

**Comment by erwan2345** [comment]
Hi 
Yes I’m currently travelling, I enjoy the today’s Amsterdam airport failure... I will modify the code as you indicated this week end I think.
Bye
    	Erwan
    
  De : Smanar <notifications@github.com>
Envoyé : mercredi, juillet 24, 2019 17:53
À : Smanar/Domoticz-deCONZ
Cc : erwan2345; Author
Objet : Re: [Smanar/Domoticz-deCONZ] Add Tradfri Switch support (#26) 

Are you still here :) ?

**Comment by Smanar** [comment]
Lol, sorry, good flight ^^.

**Comment by erwan2345** [comment]
I close this one linked to Master branch , replaced by the Beta one

**Pull request closed without merging**
