### PR TITLE
Add compatibility with Xiaomi Cube T1 & Pro T1

### PR DESCRIPTION
**Pull request by Sumd84**
The new Aqara Cube T1 & Pro T1 has a model id "lumi.remote.cagl01/cagl02".
Those have been recently added in deconz-rest-plugin  https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5838

I kept XCube_R/XCube_C for the main branch.

But for my personal needs, I defined specific XCubeProT1_R/XCubeProT1_C (also the conversion functions in function.py).
As I prefer to keep the main branch clean, I refrain from pulling those modifications.

### CODE REVIEW

**Comment by Smanar** [comment]
>But for my personal needs, I defined specific XCubeProT1_R/XCubeProT1_C (also the conversion functions in function.py).
As I prefer to keep the main branch clean, I refrain from pulling those modifications.

Yep exactly ^^, else it will trigger plugin update on domoticz user, but you can make a PR on the beta branch, this one is just for that.

>also the conversion functions in function.py

The code is working as it, or need to add convertion fonction too in fonction.py ?

**Comment by Sumd84** [comment]
>The code is working as it, or need to add convertion fonction too in fonction.py ?

Let me just double-check that only this commit works fine with my Domoticz (without other modifications).

> Yep exactly ^^, else it will trigger plugin update on domoticz user, but you can make a PR on the beta branch, this one is just for that.

Ok. Thanks for the tip 👍

**Comment by Sumd84** [comment]
Just checked on Domoticz and everything works fine.

**Comment by Smanar** [comment]
Nice, but can you make the PR on the beta branch ?

**Comment by Sumd84** [comment]
Change the PR to beta but as I am quite a noob with github maybe I didn't made the right thing xD.

**Comment by Smanar** [comment]
I can't, you need to cancel this one and remake a new PR from your fork (like you have done before) but to the branch "beta" instead of "master"

**Pull request closed without merging**
